GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MzA2NjQ3LCJpYXQiOjE3NjczMDYzNDcsImp0aSI6Ijc2NzQ3ZDQxZjVhZDRhOTk5OTM2ZGY5ODc5NWU5ZWM5IiwidXNlcl9pZCI6IjEifQ.9X9ifvOW9hAmGWw4QayY2RGvlVtHcvI6T071SUsBytA

{
    "name": "Television set",
    "description": "Such an Amamazing",
    "price": "12000.99",
    "stock": 500
}

###

DELETE  http://localhost:8000/products/2/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MTg1MTEyLCJpYXQiOjE3NjcxODQ4MTIsImp0aSI6IjU4NzZhNzI5M2QxYjRjMmM4Y2VhNjVkZDU5YWZhYTlmIiwidXNlcl9pZCI6IjEifQ.xIkYVYi_SUSpu1aiUam3WO4UhWSzrDqNC6xnXOk3ckA

{
    "name": "Television2",
    "price": 3000.00,
    "stock": 14,    
    "description": "An amazing Television"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "Jon-Doe",
    "password": "Password100@"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MTg1MTEyLCJpYXQiOjE3NjcxODQ4MTIsImp0aSI6IjU4NzZhNzI5M2QxYjRjMmM4Y2VhNjVkZDU5YWZhYTlmIiwidXNlcl9pZCI6IjEifQ.xIkYVYi_SUSpu1aiUam3WO4UhWSzrDqNC6xnXOk3ckA

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NzM5MTMwMywiaWF0IjoxNzY3MzA0OTAzLCJqdGkiOiJkZjI1ODFhNWY0ZTA0ZWYxYjQ3ZGE3ZjJiNjMwNjM1MSIsInVzZXJfaWQiOiIxIn0.Rv4WiLSTMXjcm-vVudj-1zVaqE-2GeBxW-8YQrA_kaQ"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MzcwMzA3LCJpYXQiOjE3NjczNzAwMDcsImp0aSI6ImFhZWFlMjFmZDNlYjQ2YTBiMDE2NGY3NjljMWYwZWMyIiwidXNlcl9pZCI6IjIifQ.mYaatgkOFUuhfPQ-1tiSSZJSUQsFAowN6bV8coe9tjw

###

GET http://localhost:8000/orders/1a47deda-1727-4c14-af91-1a68357083a8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MzcwMzA3LCJpYXQiOjE3NjczNzAwMDcsImp0aSI6ImFhZWFlMjFmZDNlYjQ2YTBiMDE2NGY3NjljMWYwZWMyIiwidXNlcl9pZCI6IjIifQ.mYaatgkOFUuhfPQ-1tiSSZJSUQsFAowN6bV8coe9tjw